### ISSUE TITLE
bobcat-aem-bdd set up issue (JDK related)

### ISSUE THREAD

**Issue by discovermoi** [Cognifide/bobcat-gradle-template#3]
When I am using the BDD template, all default tests are skipped and get the exception
```
**# Exception in thread "main" com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 52264**
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:712)
	at com.google.inject.internal.Errors.formatSource(Errors.java:678)
	at com.google.inject.internal.Errors.format(Errors.java:555)
	at com.google.inject.ProvisionException.getMessage(ProvisionException.java:59)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:391)
	at java.lang.Throwable.toString(Throwable.java:480)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintWriter.println(PrintWriter.java:754)
	at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:764)
	at java.lang.Throwable.printStackTrace(Throwable.java:655)
	at java.lang.Throwable.printStackTrace(Throwable.java:721)
	at gherkin.formatter.model.Result.getErrorMessage(Result.java:69)
	at gherkin.formatter.model.Result.<init>(Result.java:32)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:231)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:205)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:121)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 52264
	at com.google.inject.internal.asm.$ClassReader.readClass(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.accept(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.accept(Unknown Source)
	at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 25 more
```

**Comment by discovermoi** [comment]
For clarity, it is caused by this maven dependency "bb-cumber". if I use cucumber dependencies namely (info.cukes), this error is muted but then the application is not compiling anyways.

**Comment by mkrzyzanowski** [comment]
I've just generated the `bobcat-bdd` project and tests run (they failed but probably due to wikipedia change :)). How are you invoking your tests?
